{% set version = "1.7-16" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ade4
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ade4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ade4/ade4_{{ version }}.tar.gz
  sha256: 9bd7a25ff4fe30a32fd8f6b71909f4c638a0e2f002fc8303c0a4795423385590

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libblas
    - liblapack
    - r-mass
    - r-pixmap
    - r-sp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-pixmap
    - r-sp

test:
  commands:
    - $R -e "library('ade4')"           # [not win]
    - "\"%R%\" -e \"library('ade4')\""  # [win]

about:
  home: http://pbil.univ-lyon1.fr/ADE-4
  license: GPL-2
  summary: Tools for multivariate data analysis. Several methods are provided for the analysis (i.e., ordination) of one-table (e.g., principal component analysis, correspondence analysis), two-table (e.g., coinertia analysis, redundancy analysis), three-table (e.g., RLQ analysis) and K-table (e.g., STATIS, multiple coinertia
    analysis). The philosophy of the package is described in Dray and Dufour (2007) <doi:10.18637/jss.v022.i04>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut

# Package: ade4
# Version: 1.7-15
# Date: 2020-02-13
# Title: Analysis of Ecological Data: Exploratory and Euclidean Methods in Environmental Sciences
# Author: Stephane Dray <stephane.dray@univ-lyon1.fr>, Anne-Beatrice Dufour <anne-beatrice.dufour@univ-lyon1.fr>, and Jean Thioulouse <jean.thioulouse@univ-lyon1.fr>, with contributions from Thibaut Jombart, Sandrine Pavoine, Jean R. Lobry, Sebastien Ollier, Daniel Borcard, Pierre Legendre, Stephanie Bougeard and Aurelie Siberchicot. Based on earlier work by Daniel Chessel.
# Maintainer: Aurelie Siberchicot <aurelie.siberchicot@univ-lyon1.fr>
# Depends: R (>= 2.10)
# Imports: graphics, grDevices, methods, stats, utils, MASS, pixmap, sp
# Suggests: ade4TkGUI, adegraphics, adephylo, ape, CircStats, deldir, lattice, spdep, splancs, waveslim
# Description: Tools for multivariate data analysis. Several methods are provided for the analysis (i.e., ordination) of one-table (e.g., principal component analysis, correspondence analysis), two-table (e.g., coinertia analysis, redundancy analysis), three-table (e.g., RLQ analysis) and K-table (e.g., STATIS, multiple coinertia analysis). The philosophy of the package is described in Dray and Dufour (2007) <doi:10.18637/jss.v022.i04>.
# License: GPL (>= 2)
# URL: http://pbil.univ-lyon1.fr/ADE-4
# BugReports: https://github.com/sdray/ade4/issues
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2020-02-13 09:06:03 UTC; stephane
# Repository: CRAN
# Date/Publication: 2020-02-13 11:50:07 UTC
