{% set version = '1.7-11' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ade4
  version: {{ version|replace("-", "_") }}

source:
  fn: ade4_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ade4_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ade4/ade4_{{ version }}.tar.gz
  sha256: 4ccd799ae99bd625840b866a697c4a48adb751660470bf0d6cf9207b1927a572

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('ade4')"  # [not win]
    - "\"%R%\" -e \"library('ade4')\""  # [win]

about:
  home: 'http://pbil.univ-lyon1.fr/ADE-4, Mailing list: http://listes.univ-lyon1.fr/wws/info/adelist'

  license: GPL (>= 2)
  summary: Tools for multivariate data analysis. Several methods are provided for the analysis
    (i.e., ordination) of one-table (e.g., principal component analysis, correspondence
    analysis), two-table (e.g., coinertia analysis, redundancy analysis), three-table
    (e.g., RLQ analysis) and K-table (e.g., STATIS, multiple coinertia analysis). The
    philosophy of the package is described in Dray and Dufour (2007) <doi:10.18637/jss.v022.i04>
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
