{% set version = "1.7-15" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ade4
  version: {{ version|replace("-", "_") }}

source:
  fn: ade4_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ade4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ade4/ade4_{{ version }}.tar.gz
  sha256: 3286fa7d8c372a5596e82c970c058e4cca1139a09935f14b238ba38aa9fdfdf6

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: ade4TkGUI, adegraphics, adephylo, ape, CircStats, deldir, lattice, pixmap, sp, spdep, splancs, waveslim
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass

test:
  commands:
    - $R -e "library('ade4')"           # [not win]
    - "\"%R%\" -e \"library('ade4')\""  # [win]

about:
  home: 'http://pbil.univ-lyon1.fr/ADE-4, Mailing list: http://listes.univ-lyon1.fr/wws/info/adelist'

  license: GPL (>= 2)
  summary: Tools for multivariate data analysis. Several methods are provided for the analysis
    (i.e., ordination) of one-table (e.g., principal component analysis, correspondence
    analysis), two-table (e.g., coinertia analysis, redundancy analysis), three-table
    (e.g., RLQ analysis) and K-table (e.g., STATIS, multiple coinertia analysis). The
    philosophy of the package is described in Dray and Dufour (2007) <doi:10.18637/jss.v022.i04>.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - nick-youngblut
