{% set version = '1.7-11' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ade4
  version: {{ version|replace("-", "_") }}

source:
  fn: ade4_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ade4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ade4/ade4_{{ version }}.tar.gz
  sha256: 4ccd799ae99bd625840b866a697c4a48adb751660470bf0d6cf9207b1927a572

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass

test:
  commands:
    - $R -e "library('ade4')"           # [not win]
    - "\"%R%\" -e \"library('ade4')\""  # [win]

about:
  home: 'http://pbil.univ-lyon1.fr/ADE-4'
  license: GPL (>= 2)
  summary: Tools for multivariate data analysis. Several methods are provided for the analysis
    (i.e., ordination) of one-table (e.g., principal component analysis, correspondence
    analysis), two-table (e.g., coinertia analysis, redundancy analysis), three-table
    (e.g., RLQ analysis) and K-table (e.g., STATIS, multiple coinertia analysis). The
    philosophy of the package is described in Dray and Dufour (2007) <doi:10.18637/jss.v022.i04>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - nick-youngblut
