# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "c5zZ5Iqvdr04WxGEB1d6hpthRLWRnv7rlaVHwWyo73AbFY6lQ+LbXUD/3C4z/Yhm9D1Y+6GEvgg+rHBT7ScBHIUa9yQBPLq5yJQyjqMSPl7s+xRYn1EwaRuHGsbpksbsl93ZrvHPqzhJkgeKmAqfRMd1K2w/Rug/aI3Ohq93sHOe5VlWXtaIXbXBsa+VYOLMNa839aV4MPp67DGZlDdoTu0JmmmGbBBE0tNlenLd5Rz7IbG5WroHwpQjjEEqLO3h6fzioGpPSbE5po5UN/cRv1sL4jEqKrna2L63BiiDYyOB8vumj3ricyXf4e48KUiTzyy9udLsjXl9ZfAlUD8RLglL2GhAG7YmJUG2nxEqWUP3XAfIVXj75/i6Dt4o1i4aKFtSyfz8BAT1N4wlzZP8N6m6SavGMZ5iMEEL1sFMzRjYCyMU5BVBFwNLc9+rBCF9lyyMe0kBlvSVUQZP+BXJ3lo/j1dWvCzDYtWS+5B6AnF7zOS7Mes+kW5f0iMY+KN7bwpVFNw1HZvVuy62Mczrs6weA2r9Hcqe2i0JX70nqbkQHYvTxML26f+DJ/p7uZM+4R29YJV01DY4jDjegU3lbhxoFyPzHb/go8vAvAx/zT0M8J9DZb9qDux42Ek3f6xlfOLtXSxt4XnuNyO9K1MoWtOpa5gsmld+HVvMKUJ0H9g="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
