travis:
  secure:
    BINSTAR_TOKEN: Wwy8ah/OTwJJP3WuriNG/f1HHUtTFbRRFMr9WszvhSwpscWDDhyCoCQwXLaNur8Z9sivii2tNQcFI09nbQnZXJhez3EkA5SXjldph03oc8LLJ49hkKcTtp+oDHyAEZT8Ex9Cl3XUEHU4XHZmanl9ubV3bNv/JRYkny+C+rRckR65a+7teP1CDOgXa+xJKYZkY0AfsCielOk0vP0JBLOTTOtQLt+Itoh/Dj+UODp0EeBHTWpDjOTol8L+oGeZbkQ6H8mK3oN7HHe91Yxa9R58zhs7JfhHDoXanH9faTa1KVX2QnaQBvQGqLFY3lxDwWfFNwn7uI+iEFCsu1dmwp0Ds745QI+QViM7Up4jjByIzXYtx603EB4kuKXvCkQNUOstwS6Ao8Twu8+/I0COH+88iVU8lb7wJrnXGxo8q3uGzeCzBC/f+mja8KIahh6uhE/wptLg5t5BiuAZ41ebU5V2M5zQGTb5dcV683fH5I4edhUKCnJfQIUft1fpImO45eHRp/p9k5ICMPEJcrPPLH2/22bGfvEvi0ozVNOpeEucHfFr8FuNnNbyWXrU4YMLegVtQaYQZTZG6FP6iS5muPQz3YQ6hv9E5E+qF3gTCbV4mBsky8nQI1+9loQuBZB53asyI7WJDPUwzx2SLRyP0Zm1rUYrG6Bd9xg+IT5SXxQuyOw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
