travis:
  secure:
    BINSTAR_TOKEN: oMCqXd44VEMKV5nsGwd4ONnmQti1q+pmeBhpzYXqXHrjZ9lAa3dOlOd1JSx1cxd5G9ALLAL0mtWQ9fyZPQp9042TsWePsZ+ZRhyfN+PkbgkfXXuSqCdIYgXepapg8v4DlM6w1m9NhcghNuA7YsSv+ZiEgdmt73XkmTwKMqr3+0IJNgVaSk/mOBYUQWoC+TRJsF0vbdYxGJIv9ZFf5ay2D+mNKF/NmagT1prUxYuzLjumb9ZtV5+9gtDPdR3qdhZBE9Y7IDpQV4RYbdO+DMhy19ULi3JrdOyAWiLCCAUp/IvyIZhuc0Clnmmba1OWMBGHwBcT0VFo39+OiKwxWpFjfkerllBmVLBzNIoUEJPFvaSe7Byp784b6aX/CJwsBZG6fCmJIl0H64NgZDtX+X7WJt9gwMGGgs2fmy7V4YBdcgO95udS4B5NUqnqjYu73CJnDWGlEKH+JRI0HwhJYWdzojBdhdoDuXNrq2Pev4g7jtMxXdkkZsZEp+vQIj4yZf5lApz8ioD9hwNX8bTjGFZSbICKTb2jSspFFZjLxGA4Uiku3xL0usNOHBNNEktg+QA1zCgpuTrXt5crbvbsrgJMd8Reuf8dqpmgDPxuywUIuuMjPklweF0foxi21BNZAMyddHTPvFZhXkOT9dlze9/rtvyLaUKJu84NPWgfO51enxo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
