travis:
  secure:
    BINSTAR_TOKEN: jzPQdALCc3Ou8zUrmVIX9q273mU0yx4p+tAETt4Pq1Fruy2JwA4NeFumKYCVDZWLgZhdpVXJqv03q6StP7PH7JA/QecfxEbpv4rg3lRJc4TSGJ3CDQSR05p05mOBCm2fZJfOIQVHtndVM0CJfzG4Dh1U96hg9HFP/Lk4pl9LB96Dyce4W2nn2dC/l1D9Xg1pn6+85hhlgsyWznrO7D7u6mX5ttSahwz868gCVxP9e3pHQRjd6M70ixxuCCCNfAPhZ/ihVTmU+yPg+dAli/hbgmvxC+oteFBBH3JmBQyl5rEJwHjptn4UmVbm6zbNhz2IG9CKmAwm0S1RRzTOZunrBMS1mMdnDgM9cNaEOrH9PEKnEJDfeY238FBrEiVE6MzqaC+adxOvuR+KoDF3C2elVWxvLJ/ZC+c0tYnuZROlaDW/WZfMqaJE3lvNhnyaubURj2irrFgWCk1rZY6BG/2NsZXUCFFofFw/PvrOUsvxw76Code+of5nKknBz10ocDUPhuaiUDfqoVsIINATpuT7JSY8ImeleMRN/TkG2yGljJf7ia91JPmMlBcFOEIDePT2+U3joH9arpwsNvq3/956MFihny1TGDU/1AAQ0gboj5F0A5TiYe5Z3EiJ3+r41XPf18Be9kAnyuQcTJkOBkzHP/d3CQEwwYVf41rUHCC1Zyk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
