appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XRw+6yvLHSplQAAH2wqDXdxcBuDj+pvP5RsZcgjwU1laz5BMGxwPvnAeupTeMV6+XkmOINSWefCMMUDCcfmmILtOdJqULz1W+GcSnBjazF5TpgrTyv5G8LEBYm0e5tIj89/+faqSj36d/8s/ErESPnmHza9JcPWqX7fFkbTF6hAyszBcWJQqEpOKzbGEYNZSC3IDd1w/FuR6C8bZy2sXtT3unBmBKNUUkBVwlIIeE8Re5l7b8zhjxrHh04/syjrg4kW9W9/zQQh1IL0bRygpgVGahO2XAcGf4y1dm9MosL7UFZAE0l6y+9SlkLrBopdDYSLxLau2bM7//YGFD1R7IiXF8IiH782WEG6/IuZP772mBa9H0c1t9ncX9gYCCFKsZpxOkWvlxWD18AwfpdxDOREQlXMd+PScQc6hsRA+eNmB/K/R16s9+SpXGaYmwk8lJGX8ku+7G97Z6nZ0gQa14iXezDfzY1nS0ooXqdjYZ3eYqrIyYf/4hxSa2aeTvnCykG0ygDKUFqmtMlc9qytXJJbm6rskH9crvlmFjpsusBo+115OYdRYZ5xal+4nQ+yri0oz2Ia4tmoKzdHMCEB9C+G/DmmtQlI0JwoYQ9sIzBQLBabxT1TYCv46lCCXlbREh0GTXVJHH4JB829ozEGNcQpOqOjfRCCye3B+n7yZb4I=
conda_forge_output_validation: true
