travis:
  secure:
    BINSTAR_TOKEN: c5zZ5Iqvdr04WxGEB1d6hpthRLWRnv7rlaVHwWyo73AbFY6lQ+LbXUD/3C4z/Yhm9D1Y+6GEvgg+rHBT7ScBHIUa9yQBPLq5yJQyjqMSPl7s+xRYn1EwaRuHGsbpksbsl93ZrvHPqzhJkgeKmAqfRMd1K2w/Rug/aI3Ohq93sHOe5VlWXtaIXbXBsa+VYOLMNa839aV4MPp67DGZlDdoTu0JmmmGbBBE0tNlenLd5Rz7IbG5WroHwpQjjEEqLO3h6fzioGpPSbE5po5UN/cRv1sL4jEqKrna2L63BiiDYyOB8vumj3ricyXf4e48KUiTzyy9udLsjXl9ZfAlUD8RLglL2GhAG7YmJUG2nxEqWUP3XAfIVXj75/i6Dt4o1i4aKFtSyfz8BAT1N4wlzZP8N6m6SavGMZ5iMEEL1sFMzRjYCyMU5BVBFwNLc9+rBCF9lyyMe0kBlvSVUQZP+BXJ3lo/j1dWvCzDYtWS+5B6AnF7zOS7Mes+kW5f0iMY+KN7bwpVFNw1HZvVuy62Mczrs6weA2r9Hcqe2i0JX70nqbkQHYvTxML26f+DJ/p7uZM+4R29YJV01DY4jDjegU3lbhxoFyPzHb/go8vAvAx/zT0M8J9DZb9qDux42Ek3f6xlfOLtXSxt4XnuNyO9K1MoWtOpa5gsmld+HVvMKUJ0H9g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
