travis:
  secure:
    BINSTAR_TOKEN: wj/lDY4kqCJD/03sGmfaejbOqCzui1o5VVUzBluO9zI/YYbA4D6L0w4Wzi12dj2LM43TX30VltaKd9UkTIEr7HfJs7Z/lAdbZYXl2CEqPg/DuyB+3dq3DFztkZOzFqTtt3wFFHjOHzZpJeBEO6z+GvQ6wAkVV/rMpc09wPrrQDGjshtosRKF9ir9oxhBdSUlrLD90T+KUY/fpudIJcGmQloY3PAuq9f/0bAxSnulBely4mjSikFZDvv45yszFLzdJ/NUhYI1yjqa/R35ooGJNVsn/ndO3SEr5FiKC7UsS5EeshY4hKF7/hxn09wLZ0AsaYZ4kXpq2s9n5P5Aux/SyVk4IpRXp5svgFX5nnpW52M91PPQBGWU2cGIwgzDPEVGOAT2sJ35ALwr+Af4q77vY/K3GmRpls2TuNPCEbSRAcStoJyyum7cYcP/BP1e4TjexbbHwcabqXalbvJG3y2vHv9ULWvfRz+87n8Q9Rm3hyTe4gcNc1Xnl570qxsctXTMrxAeHSC7ba/q/rZkHXQannsWUZbYNK70uFo42uDe37MiyKL8Dek91+XOKnaFPO261F0JDwtjPQuhU6RhD6VaXCR2+XPF+UDSgC0CxvZJT5o/Z0l3ldPDbFNoJFGxEcQlUrx3f/F7COyfrNvWA6KOJGzul7UpwahDiJEnbRwKCls=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
